# Generated by Django 5.1.2 on 2024-10-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_anonymoususer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='camera_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_permission',
            field=models.BooleanField(default=True),
        ),
    ]
